/* Copyright (c) 2011, The Linux Foundation. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above
 *       copyright notice, this list of conditions and the following
 *       disclaimer in the documentation and/or other materials provided
 *       with the distribution.
 *     * Neither the name of The Linux Foundation nor the names of its
 *       contributors may be used to endorse or promote products derived
 *       from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 * BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
 * IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */
/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "loc_api_rpcgen_rpc.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat
rpc_loc_api_null_0x00050001(void *argp, void *clnt_res, CLIENT *clnt)
{
    return (clnt_call(clnt, rpc_loc_api_null,
        (xdrproc_t) xdr_void, (caddr_t) argp,
        (xdrproc_t) xdr_void, (caddr_t) clnt_res,
        TIMEOUT));
}

enum clnt_stat
rpc_loc_api_rpc_glue_code_info_remote_0x00050001(void *argp, rpc_loc_api_rpc_glue_code_info_remote_rets *clnt_res, CLIENT *clnt)
{
    return (clnt_call(clnt, rpc_loc_api_rpc_glue_code_info_remote,
        (xdrproc_t) xdr_void, (caddr_t) argp,
        (xdrproc_t) xdr_rpc_loc_api_rpc_glue_code_info_remote_rets, (caddr_t) clnt_res,
        TIMEOUT));
}

enum clnt_stat
rpc_loc_open_0x00050001(rpc_loc_open_args *argp, rpc_loc_open_rets *clnt_res, CLIENT *clnt)
{
    return (clnt_call(clnt, rpc_loc_open,
        (xdrproc_t) xdr_rpc_loc_open_args, (caddr_t) argp,
        (xdrproc_t) xdr_rpc_loc_open_rets, (caddr_t) clnt_res,
        TIMEOUT));
}

enum clnt_stat
rpc_loc_close_0x00050001(rpc_loc_close_args *argp, rpc_loc_close_rets *clnt_res, CLIENT *clnt)
{
    return (clnt_call(clnt, rpc_loc_close,
        (xdrproc_t) xdr_rpc_loc_close_args, (caddr_t) argp,
        (xdrproc_t) xdr_rpc_loc_close_rets, (caddr_t) clnt_res,
        TIMEOUT));
}

enum clnt_stat
rpc_loc_start_fix_0x00050001(rpc_loc_start_fix_args *argp, rpc_loc_start_fix_rets *clnt_res, CLIENT *clnt)
{
    return (clnt_call(clnt, rpc_loc_start_fix,
        (xdrproc_t) xdr_rpc_loc_start_fix_args, (caddr_t) argp,
        (xdrproc_t) xdr_rpc_loc_start_fix_rets, (caddr_t) clnt_res,
        TIMEOUT));
}

enum clnt_stat
rpc_loc_stop_fix_0x00050001(rpc_loc_stop_fix_args *argp, rpc_loc_stop_fix_rets *clnt_res, CLIENT *clnt)
{
    return (clnt_call(clnt, rpc_loc_stop_fix,
        (xdrproc_t) xdr_rpc_loc_stop_fix_args, (caddr_t) argp,
        (xdrproc_t) xdr_rpc_loc_stop_fix_rets, (caddr_t) clnt_res,
        TIMEOUT));
}

enum clnt_stat
rpc_loc_ioctl_0x00050001(rpc_loc_ioctl_args *argp, rpc_loc_ioctl_rets *clnt_res, CLIENT *clnt)
{
    return (clnt_call(clnt, rpc_loc_ioctl,
        (xdrproc_t) xdr_rpc_loc_ioctl_args, (caddr_t) argp,
        (xdrproc_t) xdr_rpc_loc_ioctl_rets, (caddr_t) clnt_res,
        TIMEOUT));
}

enum clnt_stat
rpc_loc_api_api_versions_0x00050001(void *argp, rpc_loc_api_api_versions_rets *clnt_res, CLIENT *clnt)
{
    return (clnt_call(clnt, rpc_loc_api_api_versions,
        (xdrproc_t) xdr_void, (caddr_t) argp,
        (xdrproc_t) xdr_rpc_loc_api_api_versions_rets, (caddr_t) clnt_res,
        TIMEOUT));
}

enum clnt_stat
rpc_loc_api_null_0x00050002(void *argp, void *clnt_res, CLIENT *clnt)
{
    return (clnt_call(clnt, rpc_loc_api_null,
        (xdrproc_t) xdr_void, (caddr_t) argp,
        (xdrproc_t) xdr_void, (caddr_t) clnt_res,
        TIMEOUT));
}

enum clnt_stat
rpc_loc_api_null_0x00050003(void *argp, void *clnt_res, CLIENT *clnt)
{
    return (clnt_call(clnt, rpc_loc_api_null,
        (xdrproc_t) xdr_void, (caddr_t) argp,
        (xdrproc_t) xdr_void, (caddr_t) clnt_res,
        TIMEOUT));
}

enum clnt_stat
rpc_loc_api_null_0x00050004(void *argp, void *clnt_res, CLIENT *clnt)
{
    return (clnt_call(clnt, rpc_loc_api_null,
        (xdrproc_t) xdr_void, (caddr_t) argp,
        (xdrproc_t) xdr_void, (caddr_t) clnt_res,
        TIMEOUT));
}

enum clnt_stat
rpc_loc_api_null_0x00050005(void *argp, void *clnt_res, CLIENT *clnt)
{
    return (clnt_call(clnt, rpc_loc_api_null,
        (xdrproc_t) xdr_void, (caddr_t) argp,
        (xdrproc_t) xdr_void, (caddr_t) clnt_res,
        TIMEOUT));
}

enum clnt_stat
rpc_loc_api_null_0x00050006(void *argp, void *clnt_res, CLIENT *clnt)
{
    return (clnt_call(clnt, rpc_loc_api_null,
        (xdrproc_t) xdr_void, (caddr_t) argp,
        (xdrproc_t) xdr_void, (caddr_t) clnt_res,
        TIMEOUT));
}
